{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "HlPqaRri4YrF",
        "outputId": "a30d9ae8-f38d-4107-f90d-1a6091cfdc0a"
      },
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "     <input type=\"file\" id=\"files-dbf6360c-2fdb-48d4-baf0-78b10e18bc09\" name=\"files[]\" multiple disabled\n",
              "        style=\"border:none\" />\n",
              "     <output id=\"result-dbf6360c-2fdb-48d4-baf0-78b10e18bc09\">\n",
              "      Upload widget is only available when the cell has been executed in the\n",
              "      current browser session. Please rerun this cell to enable.\n",
              "      </output>\n",
              "      <script>// Copyright 2017 Google LLC\n",
              "//\n",
              "// Licensed under the Apache License, Version 2.0 (the \"License\");\n",
              "// you may not use this file except in compliance with the License.\n",
              "// You may obtain a copy of the License at\n",
              "//\n",
              "//      http://www.apache.org/licenses/LICENSE-2.0\n",
              "//\n",
              "// Unless required by applicable law or agreed to in writing, software\n",
              "// distributed under the License is distributed on an \"AS IS\" BASIS,\n",
              "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
              "// See the License for the specific language governing permissions and\n",
              "// limitations under the License.\n",
              "\n",
              "/**\n",
              " * @fileoverview Helpers for google.colab Python module.\n",
              " */\n",
              "(function(scope) {\n",
              "function span(text, styleAttributes = {}) {\n",
              "  const element = document.createElement('span');\n",
              "  element.textContent = text;\n",
              "  for (const key of Object.keys(styleAttributes)) {\n",
              "    element.style[key] = styleAttributes[key];\n",
              "  }\n",
              "  return element;\n",
              "}\n",
              "\n",
              "// Max number of bytes which will be uploaded at a time.\n",
              "const MAX_PAYLOAD_SIZE = 100 * 1024;\n",
              "\n",
              "function _uploadFiles(inputId, outputId) {\n",
              "  const steps = uploadFilesStep(inputId, outputId);\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  // Cache steps on the outputElement to make it available for the next call\n",
              "  // to uploadFilesContinue from Python.\n",
              "  outputElement.steps = steps;\n",
              "\n",
              "  return _uploadFilesContinue(outputId);\n",
              "}\n",
              "\n",
              "// This is roughly an async generator (not supported in the browser yet),\n",
              "// where there are multiple asynchronous steps and the Python side is going\n",
              "// to poll for completion of each step.\n",
              "// This uses a Promise to block the python side on completion of each step,\n",
              "// then passes the result of the previous step as the input to the next step.\n",
              "function _uploadFilesContinue(outputId) {\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  const steps = outputElement.steps;\n",
              "\n",
              "  const next = steps.next(outputElement.lastPromiseValue);\n",
              "  return Promise.resolve(next.value.promise).then((value) => {\n",
              "    // Cache the last promise value to make it available to the next\n",
              "    // step of the generator.\n",
              "    outputElement.lastPromiseValue = value;\n",
              "    return next.value.response;\n",
              "  });\n",
              "}\n",
              "\n",
              "/**\n",
              " * Generator function which is called between each async step of the upload\n",
              " * process.\n",
              " * @param {string} inputId Element ID of the input file picker element.\n",
              " * @param {string} outputId Element ID of the output display.\n",
              " * @return {!Iterable<!Object>} Iterable of next steps.\n",
              " */\n",
              "function* uploadFilesStep(inputId, outputId) {\n",
              "  const inputElement = document.getElementById(inputId);\n",
              "  inputElement.disabled = false;\n",
              "\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  outputElement.innerHTML = '';\n",
              "\n",
              "  const pickedPromise = new Promise((resolve) => {\n",
              "    inputElement.addEventListener('change', (e) => {\n",
              "      resolve(e.target.files);\n",
              "    });\n",
              "  });\n",
              "\n",
              "  const cancel = document.createElement('button');\n",
              "  inputElement.parentElement.appendChild(cancel);\n",
              "  cancel.textContent = 'Cancel upload';\n",
              "  const cancelPromise = new Promise((resolve) => {\n",
              "    cancel.onclick = () => {\n",
              "      resolve(null);\n",
              "    };\n",
              "  });\n",
              "\n",
              "  // Wait for the user to pick the files.\n",
              "  const files = yield {\n",
              "    promise: Promise.race([pickedPromise, cancelPromise]),\n",
              "    response: {\n",
              "      action: 'starting',\n",
              "    }\n",
              "  };\n",
              "\n",
              "  cancel.remove();\n",
              "\n",
              "  // Disable the input element since further picks are not allowed.\n",
              "  inputElement.disabled = true;\n",
              "\n",
              "  if (!files) {\n",
              "    return {\n",
              "      response: {\n",
              "        action: 'complete',\n",
              "      }\n",
              "    };\n",
              "  }\n",
              "\n",
              "  for (const file of files) {\n",
              "    const li = document.createElement('li');\n",
              "    li.append(span(file.name, {fontWeight: 'bold'}));\n",
              "    li.append(span(\n",
              "        `(${file.type || 'n/a'}) - ${file.size} bytes, ` +\n",
              "        `last modified: ${\n",
              "            file.lastModifiedDate ? file.lastModifiedDate.toLocaleDateString() :\n",
              "                                    'n/a'} - `));\n",
              "    const percent = span('0% done');\n",
              "    li.appendChild(percent);\n",
              "\n",
              "    outputElement.appendChild(li);\n",
              "\n",
              "    const fileDataPromise = new Promise((resolve) => {\n",
              "      const reader = new FileReader();\n",
              "      reader.onload = (e) => {\n",
              "        resolve(e.target.result);\n",
              "      };\n",
              "      reader.readAsArrayBuffer(file);\n",
              "    });\n",
              "    // Wait for the data to be ready.\n",
              "    let fileData = yield {\n",
              "      promise: fileDataPromise,\n",
              "      response: {\n",
              "        action: 'continue',\n",
              "      }\n",
              "    };\n",
              "\n",
              "    // Use a chunked sending to avoid message size limits. See b/62115660.\n",
              "    let position = 0;\n",
              "    do {\n",
              "      const length = Math.min(fileData.byteLength - position, MAX_PAYLOAD_SIZE);\n",
              "      const chunk = new Uint8Array(fileData, position, length);\n",
              "      position += length;\n",
              "\n",
              "      const base64 = btoa(String.fromCharCode.apply(null, chunk));\n",
              "      yield {\n",
              "        response: {\n",
              "          action: 'append',\n",
              "          file: file.name,\n",
              "          data: base64,\n",
              "        },\n",
              "      };\n",
              "\n",
              "      let percentDone = fileData.byteLength === 0 ?\n",
              "          100 :\n",
              "          Math.round((position / fileData.byteLength) * 100);\n",
              "      percent.textContent = `${percentDone}% done`;\n",
              "\n",
              "    } while (position < fileData.byteLength);\n",
              "  }\n",
              "\n",
              "  // All done.\n",
              "  yield {\n",
              "    response: {\n",
              "      action: 'complete',\n",
              "    }\n",
              "  };\n",
              "}\n",
              "\n",
              "scope.google = scope.google || {};\n",
              "scope.google.colab = scope.google.colab || {};\n",
              "scope.google.colab._files = {\n",
              "  _uploadFiles,\n",
              "  _uploadFilesContinue,\n",
              "};\n",
              "})(self);\n",
              "</script> "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Saving gangwon_places_2sheet_join_extended.xlsx to gangwon_places_2sheet_join_extended.xlsx\n",
            "업로드한 파일: gangwon_places_2sheet_join_extended.xlsx\n",
            "장소정보 시트\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "   place_id        이름  지역  유형 실내여부   평점\n",
              "0         1  강릉 시립도서관  강릉  학습   실내  4.3\n",
              "1         2   강릉 중앙시장  강릉  음식   실내  4.2\n",
              "2         3      속초해변  속초  관광   실외  4.6\n",
              "3         4  춘천 시립도서관  춘천  학습   실내  4.1\n",
              "4         5       감자밭  춘천  카페  실내외  4.5"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-11366733-3daf-48c4-8d0b-f35e6946bee1\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>place_id</th>\n",
              "      <th>이름</th>\n",
              "      <th>지역</th>\n",
              "      <th>유형</th>\n",
              "      <th>실내여부</th>\n",
              "      <th>평점</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>1</td>\n",
              "      <td>강릉 시립도서관</td>\n",
              "      <td>강릉</td>\n",
              "      <td>학습</td>\n",
              "      <td>실내</td>\n",
              "      <td>4.3</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>2</td>\n",
              "      <td>강릉 중앙시장</td>\n",
              "      <td>강릉</td>\n",
              "      <td>음식</td>\n",
              "      <td>실내</td>\n",
              "      <td>4.2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>3</td>\n",
              "      <td>속초해변</td>\n",
              "      <td>속초</td>\n",
              "      <td>관광</td>\n",
              "      <td>실외</td>\n",
              "      <td>4.6</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>4</td>\n",
              "      <td>춘천 시립도서관</td>\n",
              "      <td>춘천</td>\n",
              "      <td>학습</td>\n",
              "      <td>실내</td>\n",
              "      <td>4.1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>5</td>\n",
              "      <td>감자밭</td>\n",
              "      <td>춘천</td>\n",
              "      <td>카페</td>\n",
              "      <td>실내외</td>\n",
              "      <td>4.5</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-11366733-3daf-48c4-8d0b-f35e6946bee1')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-11366733-3daf-48c4-8d0b-f35e6946bee1 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-11366733-3daf-48c4-8d0b-f35e6946bee1');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "  <div id=\"id_8747f7b4-3aee-4c2e-8002-54d4b5446553\">\n",
              "    <style>\n",
              "      .colab-df-generate {\n",
              "        background-color: #E8F0FE;\n",
              "        border: none;\n",
              "        border-radius: 50%;\n",
              "        cursor: pointer;\n",
              "        display: none;\n",
              "        fill: #1967D2;\n",
              "        height: 32px;\n",
              "        padding: 0 0 0 0;\n",
              "        width: 32px;\n",
              "      }\n",
              "\n",
              "      .colab-df-generate:hover {\n",
              "        background-color: #E2EBFA;\n",
              "        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "        fill: #174EA6;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate {\n",
              "        background-color: #3B4455;\n",
              "        fill: #D2E3FC;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate:hover {\n",
              "        background-color: #434B5C;\n",
              "        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "        fill: #FFFFFF;\n",
              "      }\n",
              "    </style>\n",
              "    <button class=\"colab-df-generate\" onclick=\"generateWithVariable('place_df')\"\n",
              "            title=\"Generate code using this dataframe.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "    <script>\n",
              "      (() => {\n",
              "      const buttonEl =\n",
              "        document.querySelector('#id_8747f7b4-3aee-4c2e-8002-54d4b5446553 button.colab-df-generate');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      buttonEl.onclick = () => {\n",
              "        google.colab.notebook.generateWithVariable('place_df');\n",
              "      }\n",
              "      })();\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "place_df",
              "summary": "{\n  \"name\": \"place_df\",\n  \"rows\": 5,\n  \"fields\": [\n    {\n      \"column\": \"place_id\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 1,\n        \"max\": 5,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          2,\n          5,\n          3\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc774\\ub984\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"\\uac15\\ub989 \\uc911\\uc559\\uc2dc\\uc7a5\",\n          \"\\uac10\\uc790\\ubc2d\",\n          \"\\uc18d\\ucd08\\ud574\\ubcc0\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc9c0\\uc5ed\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"\\uac15\\ub989\",\n          \"\\uc18d\\ucd08\",\n          \"\\ucd98\\ucc9c\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc720\\ud615\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 4,\n        \"samples\": [\n          \"\\uc74c\\uc2dd\",\n          \"\\uce74\\ud398\",\n          \"\\ud559\\uc2b5\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc2e4\\ub0b4\\uc5ec\\ubd80\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"\\uc2e4\\ub0b4\",\n          \"\\uc2e4\\uc678\",\n          \"\\uc2e4\\ub0b4\\uc678\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\ud3c9\\uc810\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.20736441353327717,\n        \"min\": 4.1,\n        \"max\": 4.6,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          4.2,\n          4.5,\n          4.6\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "추천정보 시트\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "    추천ID  place_id  추천목적  추천상황 추천대상     예산           추천활동   소요시간 예약필요\n",
              "0   R001         1    공부  비오는날   혼자      0         조용한 자습  2~3시간    X\n",
              "1   R002         1    독서  조용한곳   혼자      0     관심 분야 책 읽기  1~2시간    X\n",
              "2   R003         1    팀플  시험기간   친구      0  자료 조사 및 발표 준비    2시간    X\n",
              "3   R004         2    식사  저렴한곳   친구  10000       시장 음식 먹기    1시간    X\n",
              "4   R005         2    간식  비오는날   친구   5000       분식·간식 먹기    30분    X\n",
              "5   R006         2    관광    여행   가족  12000      지역 먹거리 체험  1~2시간    X\n",
              "6   R007         3    산책   맑은날   가족      0          해변 산책    1시간    X\n",
              "7   R008         3  사진촬영    노을   친구      0       바다 사진 찍기    1시간    X\n",
              "8   R009         3    휴식    여행   혼자      0       바다 보며 쉬기  1~2시간    X\n",
              "9   R010         4    공부  조용한곳   혼자      0        자습 및 과제  2~3시간    X\n",
              "10  R011         4    독서  비오는날   가족      0       가족 독서 시간    1시간    X\n",
              "11  R012         4    진로  시험기간   친구      0       진로 자료 탐색  1~2시간    X\n",
              "12  R013         5   데이트    여행   친구  15000          카페 방문  1~2시간    X\n",
              "13  R014         5  사진촬영   맑은날   친구  15000       카페 사진 찍기    1시간    X\n",
              "14  R015         5    간식    여행   가족  20000         감자빵 먹기    1시간    X"
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-51b40aa7-2587-445b-970b-3f47fcc206bb\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>추천ID</th>\n",
              "      <th>place_id</th>\n",
              "      <th>추천목적</th>\n",
              "      <th>추천상황</th>\n",
              "      <th>추천대상</th>\n",
              "      <th>예산</th>\n",
              "      <th>추천활동</th>\n",
              "      <th>소요시간</th>\n",
              "      <th>예약필요</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>R001</td>\n",
              "      <td>1</td>\n",
              "      <td>공부</td>\n",
              "      <td>비오는날</td>\n",
              "      <td>혼자</td>\n",
              "      <td>0</td>\n",
              "      <td>조용한 자습</td>\n",
              "      <td>2~3시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>R002</td>\n",
              "      <td>1</td>\n",
              "      <td>독서</td>\n",
              "      <td>조용한곳</td>\n",
              "      <td>혼자</td>\n",
              "      <td>0</td>\n",
              "      <td>관심 분야 책 읽기</td>\n",
              "      <td>1~2시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>R003</td>\n",
              "      <td>1</td>\n",
              "      <td>팀플</td>\n",
              "      <td>시험기간</td>\n",
              "      <td>친구</td>\n",
              "      <td>0</td>\n",
              "      <td>자료 조사 및 발표 준비</td>\n",
              "      <td>2시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>R004</td>\n",
              "      <td>2</td>\n",
              "      <td>식사</td>\n",
              "      <td>저렴한곳</td>\n",
              "      <td>친구</td>\n",
              "      <td>10000</td>\n",
              "      <td>시장 음식 먹기</td>\n",
              "      <td>1시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>R005</td>\n",
              "      <td>2</td>\n",
              "      <td>간식</td>\n",
              "      <td>비오는날</td>\n",
              "      <td>친구</td>\n",
              "      <td>5000</td>\n",
              "      <td>분식·간식 먹기</td>\n",
              "      <td>30분</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>R006</td>\n",
              "      <td>2</td>\n",
              "      <td>관광</td>\n",
              "      <td>여행</td>\n",
              "      <td>가족</td>\n",
              "      <td>12000</td>\n",
              "      <td>지역 먹거리 체험</td>\n",
              "      <td>1~2시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>R007</td>\n",
              "      <td>3</td>\n",
              "      <td>산책</td>\n",
              "      <td>맑은날</td>\n",
              "      <td>가족</td>\n",
              "      <td>0</td>\n",
              "      <td>해변 산책</td>\n",
              "      <td>1시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>R008</td>\n",
              "      <td>3</td>\n",
              "      <td>사진촬영</td>\n",
              "      <td>노을</td>\n",
              "      <td>친구</td>\n",
              "      <td>0</td>\n",
              "      <td>바다 사진 찍기</td>\n",
              "      <td>1시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>R009</td>\n",
              "      <td>3</td>\n",
              "      <td>휴식</td>\n",
              "      <td>여행</td>\n",
              "      <td>혼자</td>\n",
              "      <td>0</td>\n",
              "      <td>바다 보며 쉬기</td>\n",
              "      <td>1~2시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>R010</td>\n",
              "      <td>4</td>\n",
              "      <td>공부</td>\n",
              "      <td>조용한곳</td>\n",
              "      <td>혼자</td>\n",
              "      <td>0</td>\n",
              "      <td>자습 및 과제</td>\n",
              "      <td>2~3시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>10</th>\n",
              "      <td>R011</td>\n",
              "      <td>4</td>\n",
              "      <td>독서</td>\n",
              "      <td>비오는날</td>\n",
              "      <td>가족</td>\n",
              "      <td>0</td>\n",
              "      <td>가족 독서 시간</td>\n",
              "      <td>1시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>11</th>\n",
              "      <td>R012</td>\n",
              "      <td>4</td>\n",
              "      <td>진로</td>\n",
              "      <td>시험기간</td>\n",
              "      <td>친구</td>\n",
              "      <td>0</td>\n",
              "      <td>진로 자료 탐색</td>\n",
              "      <td>1~2시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>12</th>\n",
              "      <td>R013</td>\n",
              "      <td>5</td>\n",
              "      <td>데이트</td>\n",
              "      <td>여행</td>\n",
              "      <td>친구</td>\n",
              "      <td>15000</td>\n",
              "      <td>카페 방문</td>\n",
              "      <td>1~2시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>13</th>\n",
              "      <td>R014</td>\n",
              "      <td>5</td>\n",
              "      <td>사진촬영</td>\n",
              "      <td>맑은날</td>\n",
              "      <td>친구</td>\n",
              "      <td>15000</td>\n",
              "      <td>카페 사진 찍기</td>\n",
              "      <td>1시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>14</th>\n",
              "      <td>R015</td>\n",
              "      <td>5</td>\n",
              "      <td>간식</td>\n",
              "      <td>여행</td>\n",
              "      <td>가족</td>\n",
              "      <td>20000</td>\n",
              "      <td>감자빵 먹기</td>\n",
              "      <td>1시간</td>\n",
              "      <td>X</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-51b40aa7-2587-445b-970b-3f47fcc206bb')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-51b40aa7-2587-445b-970b-3f47fcc206bb button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-51b40aa7-2587-445b-970b-3f47fcc206bb');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "  <div id=\"id_539ca776-ddd9-4ce3-a3c3-ea78a8ca6921\">\n",
              "    <style>\n",
              "      .colab-df-generate {\n",
              "        background-color: #E8F0FE;\n",
              "        border: none;\n",
              "        border-radius: 50%;\n",
              "        cursor: pointer;\n",
              "        display: none;\n",
              "        fill: #1967D2;\n",
              "        height: 32px;\n",
              "        padding: 0 0 0 0;\n",
              "        width: 32px;\n",
              "      }\n",
              "\n",
              "      .colab-df-generate:hover {\n",
              "        background-color: #E2EBFA;\n",
              "        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "        fill: #174EA6;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate {\n",
              "        background-color: #3B4455;\n",
              "        fill: #D2E3FC;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate:hover {\n",
              "        background-color: #434B5C;\n",
              "        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "        fill: #FFFFFF;\n",
              "      }\n",
              "    </style>\n",
              "    <button class=\"colab-df-generate\" onclick=\"generateWithVariable('recommend_df')\"\n",
              "            title=\"Generate code using this dataframe.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "    <script>\n",
              "      (() => {\n",
              "      const buttonEl =\n",
              "        document.querySelector('#id_539ca776-ddd9-4ce3-a3c3-ea78a8ca6921 button.colab-df-generate');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      buttonEl.onclick = () => {\n",
              "        google.colab.notebook.generateWithVariable('recommend_df');\n",
              "      }\n",
              "      })();\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "recommend_df",
              "summary": "{\n  \"name\": \"recommend_df\",\n  \"rows\": 15,\n  \"fields\": [\n    {\n      \"column\": \"\\ucd94\\ucc9cID\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 15,\n        \"samples\": [\n          \"R010\",\n          \"R012\",\n          \"R001\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"place_id\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 1,\n        \"max\": 5,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          2,\n          5,\n          3\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\ucd94\\ucc9c\\ubaa9\\uc801\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 11,\n        \"samples\": [\n          \"\\uad00\\uad11\",\n          \"\\uacf5\\ubd80\",\n          \"\\uc9c4\\ub85c\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\ucd94\\ucc9c\\uc0c1\\ud669\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 7,\n        \"samples\": [\n          \"\\ube44\\uc624\\ub294\\ub0a0\",\n          \"\\uc870\\uc6a9\\ud55c\\uacf3\",\n          \"\\ub9d1\\uc740\\ub0a0\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\ucd94\\ucc9c\\ub300\\uc0c1\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"\\ud63c\\uc790\",\n          \"\\uce5c\\uad6c\",\n          \"\\uac00\\uc871\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc608\\uc0b0\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 7189,\n        \"min\": 0,\n        \"max\": 20000,\n        \"num_unique_values\": 6,\n        \"samples\": [\n          0,\n          10000,\n          20000\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\ucd94\\ucc9c\\ud65c\\ub3d9\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 15,\n        \"samples\": [\n          \"\\uc790\\uc2b5 \\ubc0f \\uacfc\\uc81c\",\n          \"\\uc9c4\\ub85c \\uc790\\ub8cc \\ud0d0\\uc0c9\",\n          \"\\uc870\\uc6a9\\ud55c \\uc790\\uc2b5\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc18c\\uc694\\uc2dc\\uac04\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"1~2\\uc2dc\\uac04\",\n          \"30\\ubd84\",\n          \"2\\uc2dc\\uac04\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc608\\uc57d\\ud544\\uc694\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 1,\n        \"samples\": [\n          \"X\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "조인 결과\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "    추천ID  place_id  추천목적  추천상황 추천대상     예산           추천활동   소요시간 예약필요  \\\n",
              "0   R001         1    공부  비오는날   혼자      0         조용한 자습  2~3시간    X   \n",
              "1   R002         1    독서  조용한곳   혼자      0     관심 분야 책 읽기  1~2시간    X   \n",
              "2   R003         1    팀플  시험기간   친구      0  자료 조사 및 발표 준비    2시간    X   \n",
              "3   R004         2    식사  저렴한곳   친구  10000       시장 음식 먹기    1시간    X   \n",
              "4   R005         2    간식  비오는날   친구   5000       분식·간식 먹기    30분    X   \n",
              "5   R006         2    관광    여행   가족  12000      지역 먹거리 체험  1~2시간    X   \n",
              "6   R007         3    산책   맑은날   가족      0          해변 산책    1시간    X   \n",
              "7   R008         3  사진촬영    노을   친구      0       바다 사진 찍기    1시간    X   \n",
              "8   R009         3    휴식    여행   혼자      0       바다 보며 쉬기  1~2시간    X   \n",
              "9   R010         4    공부  조용한곳   혼자      0        자습 및 과제  2~3시간    X   \n",
              "10  R011         4    독서  비오는날   가족      0       가족 독서 시간    1시간    X   \n",
              "11  R012         4    진로  시험기간   친구      0       진로 자료 탐색  1~2시간    X   \n",
              "12  R013         5   데이트    여행   친구  15000          카페 방문  1~2시간    X   \n",
              "13  R014         5  사진촬영   맑은날   친구  15000       카페 사진 찍기    1시간    X   \n",
              "14  R015         5    간식    여행   가족  20000         감자빵 먹기    1시간    X   \n",
              "\n",
              "          이름  지역  유형 실내여부   평점  \n",
              "0   강릉 시립도서관  강릉  학습   실내  4.3  \n",
              "1   강릉 시립도서관  강릉  학습   실내  4.3  \n",
              "2   강릉 시립도서관  강릉  학습   실내  4.3  \n",
              "3    강릉 중앙시장  강릉  음식   실내  4.2  \n",
              "4    강릉 중앙시장  강릉  음식   실내  4.2  \n",
              "5    강릉 중앙시장  강릉  음식   실내  4.2  \n",
              "6       속초해변  속초  관광   실외  4.6  \n",
              "7       속초해변  속초  관광   실외  4.6  \n",
              "8       속초해변  속초  관광   실외  4.6  \n",
              "9   춘천 시립도서관  춘천  학습   실내  4.1  \n",
              "10  춘천 시립도서관  춘천  학습   실내  4.1  \n",
              "11  춘천 시립도서관  춘천  학습   실내  4.1  \n",
              "12       감자밭  춘천  카페  실내외  4.5  \n",
              "13       감자밭  춘천  카페  실내외  4.5  \n",
              "14       감자밭  춘천  카페  실내외  4.5  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-689ca7d7-e567-4756-a3cd-e5ee7dd32ce7\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>추천ID</th>\n",
              "      <th>place_id</th>\n",
              "      <th>추천목적</th>\n",
              "      <th>추천상황</th>\n",
              "      <th>추천대상</th>\n",
              "      <th>예산</th>\n",
              "      <th>추천활동</th>\n",
              "      <th>소요시간</th>\n",
              "      <th>예약필요</th>\n",
              "      <th>이름</th>\n",
              "      <th>지역</th>\n",
              "      <th>유형</th>\n",
              "      <th>실내여부</th>\n",
              "      <th>평점</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>R001</td>\n",
              "      <td>1</td>\n",
              "      <td>공부</td>\n",
              "      <td>비오는날</td>\n",
              "      <td>혼자</td>\n",
              "      <td>0</td>\n",
              "      <td>조용한 자습</td>\n",
              "      <td>2~3시간</td>\n",
              "      <td>X</td>\n",
              "      <td>강릉 시립도서관</td>\n",
              "      <td>강릉</td>\n",
              "      <td>학습</td>\n",
              "      <td>실내</td>\n",
              "      <td>4.3</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>R002</td>\n",
              "      <td>1</td>\n",
              "      <td>독서</td>\n",
              "      <td>조용한곳</td>\n",
              "      <td>혼자</td>\n",
              "      <td>0</td>\n",
              "      <td>관심 분야 책 읽기</td>\n",
              "      <td>1~2시간</td>\n",
              "      <td>X</td>\n",
              "      <td>강릉 시립도서관</td>\n",
              "      <td>강릉</td>\n",
              "      <td>학습</td>\n",
              "      <td>실내</td>\n",
              "      <td>4.3</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>R003</td>\n",
              "      <td>1</td>\n",
              "      <td>팀플</td>\n",
              "      <td>시험기간</td>\n",
              "      <td>친구</td>\n",
              "      <td>0</td>\n",
              "      <td>자료 조사 및 발표 준비</td>\n",
              "      <td>2시간</td>\n",
              "      <td>X</td>\n",
              "      <td>강릉 시립도서관</td>\n",
              "      <td>강릉</td>\n",
              "      <td>학습</td>\n",
              "      <td>실내</td>\n",
              "      <td>4.3</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>R004</td>\n",
              "      <td>2</td>\n",
              "      <td>식사</td>\n",
              "      <td>저렴한곳</td>\n",
              "      <td>친구</td>\n",
              "      <td>10000</td>\n",
              "      <td>시장 음식 먹기</td>\n",
              "      <td>1시간</td>\n",
              "      <td>X</td>\n",
              "      <td>강릉 중앙시장</td>\n",
              "      <td>강릉</td>\n",
              "      <td>음식</td>\n",
              "      <td>실내</td>\n",
              "      <td>4.2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>R005</td>\n",
              "      <td>2</td>\n",
              "      <td>간식</td>\n",
              "      <td>비오는날</td>\n",
              "      <td>친구</td>\n",
              "      <td>5000</td>\n",
              "      <td>분식·간식 먹기</td>\n",
              "      <td>30분</td>\n",
              "      <td>X</td>\n",
              "      <td>강릉 중앙시장</td>\n",
              "      <td>강릉</td>\n",
              "      <td>음식</td>\n",
              "      <td>실내</td>\n",
              "      <td>4.2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>R006</td>\n",
              "      <td>2</td>\n",
              "      <td>관광</td>\n",
              "      <td>여행</td>\n",
              "      <td>가족</td>\n",
              "      <td>12000</td>\n",
              "      <td>지역 먹거리 체험</td>\n",
              "      <td>1~2시간</td>\n",
              "      <td>X</td>\n",
              "      <td>강릉 중앙시장</td>\n",
              "      <td>강릉</td>\n",
              "      <td>음식</td>\n",
              "      <td>실내</td>\n",
              "      <td>4.2</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>R007</td>\n",
              "      <td>3</td>\n",
              "      <td>산책</td>\n",
              "      <td>맑은날</td>\n",
              "      <td>가족</td>\n",
              "      <td>0</td>\n",
              "      <td>해변 산책</td>\n",
              "      <td>1시간</td>\n",
              "      <td>X</td>\n",
              "      <td>속초해변</td>\n",
              "      <td>속초</td>\n",
              "      <td>관광</td>\n",
              "      <td>실외</td>\n",
              "      <td>4.6</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>R008</td>\n",
              "      <td>3</td>\n",
              "      <td>사진촬영</td>\n",
              "      <td>노을</td>\n",
              "      <td>친구</td>\n",
              "      <td>0</td>\n",
              "      <td>바다 사진 찍기</td>\n",
              "      <td>1시간</td>\n",
              "      <td>X</td>\n",
              "      <td>속초해변</td>\n",
              "      <td>속초</td>\n",
              "      <td>관광</td>\n",
              "      <td>실외</td>\n",
              "      <td>4.6</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>R009</td>\n",
              "      <td>3</td>\n",
              "      <td>휴식</td>\n",
              "      <td>여행</td>\n",
              "      <td>혼자</td>\n",
              "      <td>0</td>\n",
              "      <td>바다 보며 쉬기</td>\n",
              "      <td>1~2시간</td>\n",
              "      <td>X</td>\n",
              "      <td>속초해변</td>\n",
              "      <td>속초</td>\n",
              "      <td>관광</td>\n",
              "      <td>실외</td>\n",
              "      <td>4.6</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>R010</td>\n",
              "      <td>4</td>\n",
              "      <td>공부</td>\n",
              "      <td>조용한곳</td>\n",
              "      <td>혼자</td>\n",
              "      <td>0</td>\n",
              "      <td>자습 및 과제</td>\n",
              "      <td>2~3시간</td>\n",
              "      <td>X</td>\n",
              "      <td>춘천 시립도서관</td>\n",
              "      <td>춘천</td>\n",
              "      <td>학습</td>\n",
              "      <td>실내</td>\n",
              "      <td>4.1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>10</th>\n",
              "      <td>R011</td>\n",
              "      <td>4</td>\n",
              "      <td>독서</td>\n",
              "      <td>비오는날</td>\n",
              "      <td>가족</td>\n",
              "      <td>0</td>\n",
              "      <td>가족 독서 시간</td>\n",
              "      <td>1시간</td>\n",
              "      <td>X</td>\n",
              "      <td>춘천 시립도서관</td>\n",
              "      <td>춘천</td>\n",
              "      <td>학습</td>\n",
              "      <td>실내</td>\n",
              "      <td>4.1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>11</th>\n",
              "      <td>R012</td>\n",
              "      <td>4</td>\n",
              "      <td>진로</td>\n",
              "      <td>시험기간</td>\n",
              "      <td>친구</td>\n",
              "      <td>0</td>\n",
              "      <td>진로 자료 탐색</td>\n",
              "      <td>1~2시간</td>\n",
              "      <td>X</td>\n",
              "      <td>춘천 시립도서관</td>\n",
              "      <td>춘천</td>\n",
              "      <td>학습</td>\n",
              "      <td>실내</td>\n",
              "      <td>4.1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>12</th>\n",
              "      <td>R013</td>\n",
              "      <td>5</td>\n",
              "      <td>데이트</td>\n",
              "      <td>여행</td>\n",
              "      <td>친구</td>\n",
              "      <td>15000</td>\n",
              "      <td>카페 방문</td>\n",
              "      <td>1~2시간</td>\n",
              "      <td>X</td>\n",
              "      <td>감자밭</td>\n",
              "      <td>춘천</td>\n",
              "      <td>카페</td>\n",
              "      <td>실내외</td>\n",
              "      <td>4.5</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>13</th>\n",
              "      <td>R014</td>\n",
              "      <td>5</td>\n",
              "      <td>사진촬영</td>\n",
              "      <td>맑은날</td>\n",
              "      <td>친구</td>\n",
              "      <td>15000</td>\n",
              "      <td>카페 사진 찍기</td>\n",
              "      <td>1시간</td>\n",
              "      <td>X</td>\n",
              "      <td>감자밭</td>\n",
              "      <td>춘천</td>\n",
              "      <td>카페</td>\n",
              "      <td>실내외</td>\n",
              "      <td>4.5</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>14</th>\n",
              "      <td>R015</td>\n",
              "      <td>5</td>\n",
              "      <td>간식</td>\n",
              "      <td>여행</td>\n",
              "      <td>가족</td>\n",
              "      <td>20000</td>\n",
              "      <td>감자빵 먹기</td>\n",
              "      <td>1시간</td>\n",
              "      <td>X</td>\n",
              "      <td>감자밭</td>\n",
              "      <td>춘천</td>\n",
              "      <td>카페</td>\n",
              "      <td>실내외</td>\n",
              "      <td>4.5</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-689ca7d7-e567-4756-a3cd-e5ee7dd32ce7')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-689ca7d7-e567-4756-a3cd-e5ee7dd32ce7 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-689ca7d7-e567-4756-a3cd-e5ee7dd32ce7');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "  <div id=\"id_ec984abd-845b-4c60-8582-a8893bbf52ff\">\n",
              "    <style>\n",
              "      .colab-df-generate {\n",
              "        background-color: #E8F0FE;\n",
              "        border: none;\n",
              "        border-radius: 50%;\n",
              "        cursor: pointer;\n",
              "        display: none;\n",
              "        fill: #1967D2;\n",
              "        height: 32px;\n",
              "        padding: 0 0 0 0;\n",
              "        width: 32px;\n",
              "      }\n",
              "\n",
              "      .colab-df-generate:hover {\n",
              "        background-color: #E2EBFA;\n",
              "        box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "        fill: #174EA6;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate {\n",
              "        background-color: #3B4455;\n",
              "        fill: #D2E3FC;\n",
              "      }\n",
              "\n",
              "      [theme=dark] .colab-df-generate:hover {\n",
              "        background-color: #434B5C;\n",
              "        box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "        filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "        fill: #FFFFFF;\n",
              "      }\n",
              "    </style>\n",
              "    <button class=\"colab-df-generate\" onclick=\"generateWithVariable('merged_df')\"\n",
              "            title=\"Generate code using this dataframe.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "       width=\"24px\">\n",
              "    <path d=\"M7,19H8.4L18.45,9,17,7.55,7,17.6ZM5,21V16.75L18.45,3.32a2,2,0,0,1,2.83,0l1.4,1.43a1.91,1.91,0,0,1,.58,1.4,1.91,1.91,0,0,1-.58,1.4L9.25,21ZM18.45,9,17,7.55Zm-12,3A5.31,5.31,0,0,0,4.9,8.1,5.31,5.31,0,0,0,1,6.5,5.31,5.31,0,0,0,4.9,4.9,5.31,5.31,0,0,0,6.5,1,5.31,5.31,0,0,0,8.1,4.9,5.31,5.31,0,0,0,12,6.5,5.46,5.46,0,0,0,6.5,12Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "    <script>\n",
              "      (() => {\n",
              "      const buttonEl =\n",
              "        document.querySelector('#id_ec984abd-845b-4c60-8582-a8893bbf52ff button.colab-df-generate');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      buttonEl.onclick = () => {\n",
              "        google.colab.notebook.generateWithVariable('merged_df');\n",
              "      }\n",
              "      })();\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "merged_df",
              "summary": "{\n  \"name\": \"merged_df\",\n  \"rows\": 15,\n  \"fields\": [\n    {\n      \"column\": \"\\ucd94\\ucc9cID\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 15,\n        \"samples\": [\n          \"R010\",\n          \"R012\",\n          \"R001\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"place_id\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 1,\n        \"max\": 5,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          2,\n          5,\n          3\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\ucd94\\ucc9c\\ubaa9\\uc801\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 11,\n        \"samples\": [\n          \"\\uad00\\uad11\",\n          \"\\uacf5\\ubd80\",\n          \"\\uc9c4\\ub85c\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\ucd94\\ucc9c\\uc0c1\\ud669\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 7,\n        \"samples\": [\n          \"\\ube44\\uc624\\ub294\\ub0a0\",\n          \"\\uc870\\uc6a9\\ud55c\\uacf3\",\n          \"\\ub9d1\\uc740\\ub0a0\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\ucd94\\ucc9c\\ub300\\uc0c1\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"\\ud63c\\uc790\",\n          \"\\uce5c\\uad6c\",\n          \"\\uac00\\uc871\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc608\\uc0b0\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 7189,\n        \"min\": 0,\n        \"max\": 20000,\n        \"num_unique_values\": 6,\n        \"samples\": [\n          0,\n          10000,\n          20000\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\ucd94\\ucc9c\\ud65c\\ub3d9\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 15,\n        \"samples\": [\n          \"\\uc790\\uc2b5 \\ubc0f \\uacfc\\uc81c\",\n          \"\\uc9c4\\ub85c \\uc790\\ub8cc \\ud0d0\\uc0c9\",\n          \"\\uc870\\uc6a9\\ud55c \\uc790\\uc2b5\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc18c\\uc694\\uc2dc\\uac04\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"1~2\\uc2dc\\uac04\",\n          \"30\\ubd84\",\n          \"2\\uc2dc\\uac04\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc608\\uc57d\\ud544\\uc694\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 1,\n        \"samples\": [\n          \"X\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc774\\ub984\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 5,\n        \"samples\": [\n          \"\\uac15\\ub989 \\uc911\\uc559\\uc2dc\\uc7a5\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc9c0\\uc5ed\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"\\uac15\\ub989\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc720\\ud615\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 4,\n        \"samples\": [\n          \"\\uc74c\\uc2dd\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\uc2e4\\ub0b4\\uc5ec\\ubd80\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 3,\n        \"samples\": [\n          \"\\uc2e4\\ub0b4\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"\\ud3c9\\uc810\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.1919821420266553,\n        \"min\": 4.1,\n        \"max\": 4.6,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          4.2\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {}
        }
      ],
      "source": [
        "import pandas as pd\n",
        "from google.colab import files\n",
        "\n",
        "# 1. 엑셀 파일 업로드\n",
        "uploaded = files.upload()\n",
        "\n",
        "# 2. 업로드한 파일 이름 가져오기\n",
        "file_name = list(uploaded.keys())[0]\n",
        "\n",
        "print(\"업로드한 파일:\", file_name)\n",
        "\n",
        "# 3. 엑셀 파일에서 두 시트 읽기\n",
        "place_df = pd.read_excel(file_name, sheet_name=\"장소정보\")\n",
        "recommend_df = pd.read_excel(file_name, sheet_name=\"추천정보\")\n",
        "\n",
        "# 4. 원본 데이터 확인\n",
        "print(\"장소정보 시트\")\n",
        "display(place_df)\n",
        "\n",
        "print(\"추천정보 시트\")\n",
        "display(recommend_df)\n",
        "\n",
        "# 5. place_id를 기준으로 두 데이터프레임 조인\n",
        "merged_df = pd.merge(\n",
        "    recommend_df,\n",
        "    place_df,\n",
        "    on=\"place_id\",\n",
        "    how=\"left\"\n",
        ")\n",
        "\n",
        "# 6. 조인 결과 확인\n",
        "print(\"조인 결과\")\n",
        "display(merged_df)"
      ]
    }
  ]
}
